export const listBks = [
  { id: 1, name: 'BDO Unibank' },
  { id: 2, name: 'Land Bank of the Philippines' },
  { id: 3, name: 'Bank of the Philippine Islands (BPI)' },
  { id: 4, name: 'Metrobank' },
  { id: 5, name: 'Philippine National Bank (PNB)' },
  { id: 6, name: 'Security Bank' },
  { id: 7, name: 'UnionBank' },
  { id: 8, name: 'China Bank' },
  { id: 9, name: 'EastWest Bank' },
  { id: 10, name: 'RCBC (Rizal Commercial Banking Corporation)' },
  { id: 11, name: 'UCPB (United Coconut Planters Bank)' },
  { id: 12, name: 'Philtrust Bank' },
  { id: 13, name: 'DBP (Development Bank of the Philippines)' },
  { id: 14, name: 'Asia United Bank' },
  { id: 15, name: 'PSBank (Philippine Savings Bank)' },
  { id: 16, name: 'Sterling Bank of Asia' },
  { id: 17, name: 'Maybank Philippines' },
  { id: 18, name: 'Bank of Commerce' },
  { id: 19, name: 'Robinsons Bank' },
  { id: 20, name: 'Philippine Bank of Communications (PBCom)' },
  { id: 21, name: 'PNB Savings Bank' },
  { id: 22, name: 'Security Bank Savings' },
  { id: 23, name: 'CIMB Bank Philippines' },
  { id: 24, name: 'Tonik Digital Bank' },
  { id: 25, name: 'ING Philippines' },
  { id: 26, name: 'HSBC Philippines' },
  { id: 27, name: 'Citibank Philippines' },
  { id: 28, name: 'Standard Chartered Bank' },
  { id: 29, name: 'Equicom Savings Bank' },
  { id: 30, name: 'Philippine Veterans Bank' }
];
