export const listBks = [
  { id: 1, name: 'Barclays Bank', logo: 'https://i.imgur.com/8HhN6ZV.png' },
  { id: 2, name: 'HSBC UK', logo: 'https://i.imgur.com/Mal8RKC.jpeg' },
  { id: 3, name: 'Lloyds Bank', logo: 'https://i.imgur.com/5rmRHsL.jpeg' },
  { id: 4, name: 'NatWest', logo: 'https://i.imgur.com/cFYhhbQ.jpeg' },
  { id: 5, name: 'Royal Bank of Scotland', logo: 'https://i.imgur.com/T7VNWea.png' },
  { id: 6, name: 'Santander UK', logo: 'https://i.imgur.com/PAL2WFa.jpeg' },
  { id: 7, name: 'Nationwide Building Society', logo: 'https://i.imgur.com/vdAEawF.png' },
  { id: 8, name: 'TSB Bank', logo: 'https://i.imgur.com/r3teXIP.png' },
  { id: 9, name: 'Metro Bank', logo: 'https://i.imgur.com/v1r65b2.jpeg' },
  { id: 10, name: 'Virgin Money UK', logo: 'https://i.imgur.com/SjTIG33.png' },
  { id: 11, name: 'Monzo Bank', logo: 'https://i.imgur.com/0iY3fGx.png' },
  { id: 12, name: 'Starling Bank', logo: 'https://i.imgur.com/m6qu8jy.jpeg' },
  { id: 13, name: 'Clydesdale Bank', logo: 'https://i.imgur.com/ActdEz4.png' },
  { id: 14, name: 'The Co-operative Bank', logo: 'https://i.imgur.com/NDiSZCv.jpeg' },
  { id: 15, name: 'Bank of Scotland', logo: 'https://i.imgur.com/5miDK69.jpeg' },
  { id: 16, name: 'Yorkshire Bank', logo: 'https://i.imgur.com/QMFFZyc.png' },
  { id: 17, name: 'Handelsbanken UK', logo: 'https://i.imgur.com/z8gLs8F.png' },
  { id: 18, name: 'Aldermore Bank', logo: 'https://i.imgur.com/NwcNhCn.png' },
  { id: 19, name: 'Close Brothers', logo: 'https://i.imgur.com/jqPEjKU.png' },
  { id: 20, name: 'Shawbrook Bank', logo: 'https://i.imgur.com/3lDAlxV.png' },
  { id: 21, name: 'Atom Bank', logo: 'https://i.imgur.com/W69OXm2.png' },
  { id: 22, name: 'Tide', logo: 'https://i.imgur.com/QDHyWyl.png' },
  { id: 23, name: 'Triodos Bank', logo: 'https://i.imgur.com/QYlgd2x.png' },
  { id: 24, name: 'Charity Bank', logo: 'https://i.imgur.com/3zzLhZT.png' },
  { id: 25, name: 'OneSavings Bank', logo: 'https://i.imgur.com/XFMPFtt.png' },
  { id: 26, name: 'Tesco Bank', logo: 'https://i.imgur.com/tZ2BLTG.png' },
  { id: 27, name: "Sainsbury's Bank", logo: 'https://i.imgur.com/UpMiR8g.png' },
  { id: 28, name: 'Bank of Ireland UK', logo: 'https://i.imgur.com/LJ6x2UP.png' },
  { id: 29, name: 'Paragon Bank', logo: 'https://i.imgur.com/lLYUn5V.png' },
  { id: 30, name: 'Coventry Building Society', logo: 'https://i.imgur.com/n1OOsK2.png' }
];
